# service name
service: busca-cep
# framework version
frameworkVersion: '2'
# cloud provider config
provider:
  # cloud provider name
  name: aws
  # lambda runtime choosen
  runtime: nodejs14.x
  # lambda hashing version (keep the wame generated)
  lambdaHashingVersion: 20201221
  # AWS configure profile
  profile: [ Nome do seu AWS CLI Profile aqui ]
  # code stage
  stage: dev
  # AWS region
  region: us-east-1
  # Amazon S3 bucket to deployment
  deploymentBucket: [ Bucket do S3 para deploy aqui ]
  # Memory configuration min 128 mb max 10240 mb
  memorySize: 4096
  # Lambda timeout
  timeout: 28
  # IAM Role
  iam:
    role: [ ARN do IAM Role aqui ]
# details about funcion
functions:
  # function
  buscaCEP:
    # handler
    handler: handler.buscaCEP
    # function name
    name: ${self:service}-${self:provider.stage}